### ISSUE TITLE
ModuleNotFoundError: No module named 

### ISSUE THREAD

**Issue by kerim371** [sizmailov/pybind11-stubgen#56]
Hi,

I have built test .pyd library using pybind11 and currently I'm looking for a way to generate .pyi files to make available autocompletions with vscode pylance.

I have `HFGt.pyd` in current folder and I'm running:
`pybind11-stubgen -o doc_py HFGt.pyd`
and get error:
```bash
Traceback (most recent call last):
  File "c:\users\tasik\.julia\conda\3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\tasik\.julia\conda\3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\tasik\.julia\conda\3\Scripts\pybind11-stubgen.exe\__main__.py", line 7, in <module>
  File "c:\users\tasik\.julia\conda\3\lib\site-packages\pybind11_stubgen\__init__.py", line 915, in main
    _module = ModuleStubsGenerator(_module_name)
  File "c:\users\tasik\.julia\conda\3\lib\site-packages\pybind11_stubgen\__init__.py", line 666, in __init__
    self.module = importlib.import_module(module_or_module_name)
  File "c:\users\tasik\.julia\conda\3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'HFGt'
```
I also tried addind/removing suffixes but it didn't help.

My library depends on two DLL files that are also in the same folder. So I'm able to import my module in test it in debug mode. What do I miss?

**Comment by sizmailov** [comment]
Hi! 

`pybind11-stubgen` does nothing special about binary modules, it simply utilizes python import machinery. Make sure the troubling module is properly installed. 

If you are working with dev version of the package and it's not installed you might need to set up some env variables to make python import your module. Not sure they are on windows, on linux it's `PYTHONPATH`/`LD_LIBRARY_PATH`

**Comment by kerim371** [comment]
@sizmailov as always I tried everything besides the advice I got without any success. When there is nothing left I tried to `set PYTHONPATH=path/to/file.pyd` and it worked :) It gave me another error but now I know that it loads the module
